### ISSUE TITLE
Build doesn't exit with error after failed webpack

### ISSUE THREAD

**Issue by ThaNarie** [hjeti/vue-skeleton#47]
https://github.com/hjeti/vue-skeleton/blob/e0161ded5009002007b92c6febb9439921a414c4/build-tools/script/build.js#L19

This line only throws when there is an actual JS error.

Below you can see errors that are webpack build errors (that don't throw), that are available in the `stats` object.

To have this properly work, we need to check the `stats` object for any errors, and **throw an error** after logging it.

```
[1m[31mERROR in ./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?{"localIdentName":"[local]-[hash:base64:7]","importLoaders":true,"camelCase":true,"modules":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-01964e59","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js?{"data":"@import /"src/asset/style/utils.scss/";","includePaths":["src/asset/style"]}!./src/App/App.scss
Module build failed: ModuleBuildError: Module build failed: Error: Missing binding source/frontend/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (source/frontend/node_modules/node-sass/lib/binding.js:15:13)
    at Object. (source/frontend/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object. (source/frontend/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at runLoaders (source/frontend/node_modules/webpack/lib/NormalModule.js:195:19)
    at source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (source/frontend/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (source/frontend/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (source/frontend/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (source/frontend/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (source/frontend/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (source/frontend/node_modules/webpack/lib/NormalModule.js:275:15)
 @ ./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?{"localIdentName":"[local]-[hash:base64:7]","importLoaders":true,"camelCase":true,"modules":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-01964e59","scoped":false,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js?{"data":"@import /"src/asset/style/utils.scss/";","includePaths":["src/asset/style"]}!./src/App/App.scss
 @ ./src/App/App.vue
 @ ./src/App/index.js
 @ ./src/bootstrap.js[39m[22m

You can preview your build by running: yarn preview
You can analyze your build by running: yarn analyze

Webpack Bundle Analyzer saved stats file to source/frontend/stats.json

source/frontend> cp -pr dist/* $DEPLOY_PATH/web/
Exit code: 0 (141475ms)
```

**Comment by flut1** [comment]
You can use `stats.hasErrors()`

**Comment by flut1** [comment]
More info: https://webpack.js.org/api/node/#error-handling
